export const elements = [
    ["\`","Key1","L5"],
    ["1","Key1","L5"],
    ["2","Key1","L5"],
    ["3","Key1","L4"],
    ["4","Key1","L3"],
    ["5","Key1","L2"],
    ["6","Key1","L2"],
    ["7","Key1","R2"],
    ["8","Key1","R2"],
    ["9","Key1","R3"],
    ["0","Key1","R4"],
    ["-","Key1","R5"],
    ["=","Key1","R5"],
    ["Backspace","Key6","R5", false],
    ["Tab","Key2","L5", false],
    ["Q","Key1","L5"],
    ["W","Key1","L4"],
    ["E","Key1","L3"],
    ["R","Key1","L2"],
    ["T","Key1","L2"],
    ["Y","Key1","R2"],
    ["U","Key1","R2"],
    ["I","Key1","R3"],
    ["O","Key1","R4"],
    ["P","Key1","R5"],
    ["[","Key1","R5"],
    ["]","Key1","R5"],
    ["","Key3","R5", false],
    ["","Key9","L5", false],
    ["A","Key1","L5"],
    ["S","Key1","L4"],
    ["D","Key1","L3"],
    ["F","Key1","L2"],
    ["G","Key1","L2"],
    ["H","Key1","R2"],
    ["J","Key1","R2"],
    ["K","Key1","R3"],
    ["L","Key1","R4"],
    [";","Key1","R5"],
    ["'","Key1","R5"],
    ["Enter","Key7","R5", false],
    ["Shift","Key10","L5", false],
    ["Z","Key1","L5"],
    ["X","Key1","L4"],
    ["C","Key1","L3"],
    ["V","Key1","L2"],
    ["B","Key1","L2"],
    ["N","Key1","R2"],
    ["M","Key1","R2"],
    [",","Key1","R3"],
    [".","Key1","R4"],
    ["/","Key1","R5"],
    ["Shift","Key8","R5", false],
    ["","Key1","Out", false],
    ["Ctrl","Key2","L5", false],
    ["Fn","Key1","Out", false],
    ["","Key1","Out", false],
    ["Alt","Key4","L5",false],
    ["","Key5","L1", false],
    ["Alt","Key4","R5", false],
    ["Ctrl","Key2","R5", false],
    ["Alt","Key1","R5", false],
    ["","Key1","Out", false],
    ["","Key1","Out", false]
];
